twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        languages: ["en","fr"]
        pages : ["profil","teams","account"]
        navs : ["home","findteam","findplayers","quizz","profil"]
    form_themes: ['bootstrap_4_layout.html.twig']
